name: Scala CI

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
 check-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Check formatting
      working-directory: ./app
      run: sbt scalafmtCheckAll
 run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run tests
      working-directory: ./app
      run: sbt test
 sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Build coverage
        run: sbt jacoco
        working-directory: ./app
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONARCLOUD_TOKEN: ${{ secrets.SONAR_TOKEN }}