name: Scala CI

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  reformat-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jrouly/scalafmt-native-action@v2
      with:
        version: '3.6.0'
        arguments: '.'
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
  test:
    needs: reformat-code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run tests
      run: sbt test
