name: Scala CI

on:
  push:
    branches: [ "feature/**", "bugfix/**" ]

permissions:
  contents: write

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jrouly/scalafmt-native-action@v2
      with:
        version: '3.6.0'
        arguments: '.'
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
     commit_message: Formatted code